### ISSUE TITLE
Code Style Standard

### ISSUE THREAD

**Issue by ispringle** [plusuncold/epub-bouncer#4]
How do you want to handle code styling? I personally prefer `flake8` to `pep8` for tooling, and I also a a proponent of `black`.

**Comment by plusuncold** [comment]
I'll set up `flake8`. I'm not sure about `black` but it'll be a lot easier to do it now, rather than later so let's go for it.

**Comment by plusuncold** [comment]
Added `flake8` with pre-commit hooks, so it'll check that it passes before committing. Source for setup here: https://ljvmiranda921.github.io/notebook/2018/06/21/precommits-using-black-and-flake8/

I decided against `black` because I don't want to many reqs for development. This way we only have `flake8` and `pre-commit` - which I should really split out into a `requirements-dev.txt`.

**Comment by ispringle** [comment]
Wonderful. I am sure that there are other things to consider, but I like to fly fast and loose and throw standards to the wind, so I'm not sure what those things might be.
